### ISSUE TITLE
Implement David's maximum current extractor with interpolation

### ISSUE THREAD

**Issue by theHenks** [legend-exp/LegendDSP.jl#12]
@hervasa2 has a nice analytical way how to extract the current maximum while interpolating the with a second order polynominal. Could first go into `LegendDSP.jl` and  then maybe later go into `RadiationDetectorDSP.jl` . Could maybe also included in the PoliDNI functionality which then instead of returning a pick-off at at fixed position gives back the maximum after interpolation? @oschulz what do you think about this?

**Comment by oschulz** [comment]
> Could maybe also included in the PoliDNI functionality which then instead of returning a pick-off at at fixed position gives back the maximum after interpolation?

Yes, I've been thinking about doing something in that direction (polynomial interpolation for max-finding) for a while, certainly a nice addition.
