### ISSUE TITLE
COAX analysis dsp parameters

### ISSUE THREAD

**Issue by esleon97** [legend-exp/LegendDSP.jl#33]
The COAX detector PSD for Nu24 will rely on an artificial neural network (ANN) complemented by a 10-90 % rise time cut. It follows the method used for COAX detectors in GERDA (see [GSTR-18-003](https://legend-exp.atlassian.net/wiki/spaces/LEGEND/pages/867237965/Pulse+Shape+Discrimination+Efficiency+Systematics), sec 2.1). Here is the procedure on how to produce the necessary dsp parameters for the COAX analysis:

1. Upsample the pole-zero corrected windowed waveform ```wf_pz_win``` by a factor of 16. Specific processor used for this can be found [here](https://github.com/legend-exp/dspeed/blob/main/src/dspeed/processors/upsampler.py).
2. Smooth out the upsampled waveform by performing 3 moving-average windows of length 48 samples, alternating between the left and the right. Specific processor used for this can be found [here](https://github.com/legend-exp/dspeed/blob/main/src/dspeed/processors/moving_windows.py).
3. Calculate ```tp_01, tp_03, tp_05, ..., tp_99``` from the smoothed waveform using ```trapEmax``` as the waveform amplitude reference value. The search of the various time points has to be done using linear interpolation.
4. Center all the time point values around ```tp_50```.

The input to the ANN is the array of centered time points ```tp_ann```.  The 10-90% rise time ```rt10_90``` is also calculated from this array.

**Comment by theHenks** [comment]
@apmypb Send final results to @esleon97 and do final cross-check

**Comment by theHenks** [comment]
After discussion with @apmypb and  @esleon97 , we can close this
